### ISSUE TITLE
problem with yarn solana:build:program on project clone locally

### ISSUE THREAD

**Issue by MirciaGeorge** [figment-networks/learn-web3-dapp#245]
When I run this command in VS Code terminal: yarn solana:build:program I got this error: Failed to install bpf-tools: HTTP status client error (404 Not Found) for url (https://github.com/solana-labs/bpf-tools/releases/download/v1.21/solana-bpf-tools-windows.tar.bz2). Do you have some ideas on how to solve this?

**Comment by icepaq** [comment]
When I tried running that command, I got a different error saying that Solana rust bpf is not available on windows. 

I have seen in the past lots of people had issues working with Solana contracts on windows. The best way to get around this error and any possible issues in the future is to use the Windows Subsystem for Linux. It's an awesome tool that allows you to run Linux commands and programs in a Windows environment.

You can get started with it here: https://docs.microsoft.com/en-us/learn/modules/get-started-with-windows-subsystem-for-linux/

**Comment by pyr0gan** [comment]
@MirciaGeorge @icepaq The Solana BPF toolchain is not & will not be available for Windows. 

We made [a quick guide to installing WSL](https://docs.figment.io/network-documentation/extra-guides/solana-setup-for-windows) so that Windows users could still compile Solana programs.

Alternatively, you can use a [Gitpod](https://gitpod.io) workspace to compile Solana programs if you are unable to run WSL 😄

**Comment by MirciaGeorge** [comment]
Thanks  guys
